### ISSUE TITLE
希望支持CustomURL, CustomPath

### ISSUE THREAD

**Issue by tian-yan** [YunfengGao/picgo-plugin-huawei-uploader#2]
希望能支持CustomURL，用来替换上传成功后返回的链接中的华为OBS桶域名。
再能支持CustomPath就更好了。 多谢。

**Comment by YunfengGao** [comment]
CustomURL在1.0.7版本支持了，欢迎试用。
至于CustomPath，建议安装[picgo-plugin-rename-file](https://github.com/liuwave/picgo-plugin-rename-file)插件，来实现自定义path的效果。

**Comment by tian-yan** [comment]
我用的是PicGo-Core命令行的(不是GUI的)，已经支持CustomURL 了？

**Comment by YunfengGao** [comment]
> 我用的是PicGo-Core命令行的(不是GUI的)，已经支持CustomURL 了？

是的，下载最新版本试试

![image](https://user-images.githubusercontent.com/7474508/136664487-29475f31-dfac-4a34-99ff-2272ac40ace8.png)

**Comment by tian-yan** [comment]
PicGo-Core配合最新版huaweicloud插件，刚才测试了customDomain功能，倍儿好用，多谢！
