### ISSUE TITLE
能不能加一个自动归档功能

### ISSUE THREAD

**Issue by cirry** [YunfengGao/picgo-plugin-huawei-uploader#3]
在picgo中有一个minio的插件就有这个自动归档功能
比如：2022/4/7号上传的文件会自动设置上传路径为/2022/04/07的文件夹下，比较方便管理

**Comment by YunfengGao** [comment]
> 在picgo中有一个minio的插件就有这个自动归档功能 比如：2022/4/7号上传的文件会自动设置上传路径为/2022/04/07的文件夹下，比较方便管理

可以fork这个插件给自己的版本做改进，或者提交PR ;)
